import { expect, test } from "@playwright/test";
import path from "path";
import { existsSync } from "fs";
import { fileURLToPath, pathToFileURL } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Resolve which HTML file to test against.
// Priority:
//   1. `GITNEXUS_HTML_PATH` env var — absolute path to an `index.html`
//      generated by `gitnexus generate html`. Useful for CI or for
//      pointing the suite at an external project (e.g. D:\taf\Alise_v2).
//   2. The gitnexus-rs self-generated docs at `<workspace>/.gitnexus/docs/index.html`.
const envPath = process.env.GITNEXUS_HTML_PATH;
const defaultPath = path.resolve(
  __dirname,
  "../../../../.gitnexus/docs/index.html"
);
const htmlPath = envPath ?? defaultPath;
const htmlUrl = pathToFileURL(htmlPath).href;

// Skip the whole suite if the HTML file isn't present — generating it
// is a prerequisite, not part of the test run, and we don't want to
// hard-fail CI on unrelated projects that happen to lack a generated
// doc.
test.describe("DeepWiki HTML Output", () => {
  test.skip(
    !existsSync(htmlPath),
    `GitNexus HTML not found at ${htmlPath}. Run 'gitnexus generate html' first or set GITNEXUS_HTML_PATH.`
  );

  test("loads the generated documentation", async ({ page }) => {
    await page.goto(htmlUrl);

    // Project name is interpolated into the title, so match loosely.
    await expect(page).toHaveTitle(/Documentation/i);

    // The DeepWiki template renders a header with the project name
    // and a stats area. The exact markup changes between versions, so
    // we just check that the header rendered and contains *something*.
    await expect(page.locator(".header").first()).toBeVisible();
    await expect(page.locator(".stats").first()).toBeVisible();

    // And that the sidebar populated (dynamic JS-driven).
    await expect(page.locator(".sidebar").first()).toBeVisible();
  });

  test("can switch to dark/light theme", async ({ page }) => {
    await page.goto(htmlUrl);

    const themeBtn = page.getByRole("button", { name: /Theme/i });
    await themeBtn.click();

    // Check if data-theme changed (accept any value — the page may
    // default to either theme depending on the OS preference).
    await expect(page.locator("html")).toHaveAttribute("data-theme", /.+/);
  });

  test("mermaid diagrams render on a diagram-bearing page", async ({ page }) => {
    await page.goto(htmlUrl);

    // Navigate to any page that has at least one mermaid diagram.
    // The concrete page names depend on what GitNexus found in the
    // indexed project — we try a few likely candidates in order.
    const candidates = [
      "processes/courriers",
      "processes/paiements-lifecycle",
      "aspnet-seq-http",
      "aspnet-seq-data",
      "architecture",
    ];
    let navigated = false;
    for (const slug of candidates) {
      const link = page.locator(`.sidebar a[data-page='${slug}']`).first();
      if ((await link.count()) > 0) {
        await link.click();
        navigated = true;
        break;
      }
    }
    test.skip(!navigated, "No mermaid-bearing page found in sidebar");

    // The mermaid container must appear. We don't assert on the modal
    // because the modal open path is programmatic (openMermaidModal)
    // and tightly coupled to Mermaid's own SVG rendering, which
    // doesn't play nicely with Playwright's synthetic clicks across
    // different DeepWiki template versions.
    const mermaidDiv = page.locator(".mermaid").first();
    await expect(mermaidDiv).toBeVisible({ timeout: 15000 });

    // Sanity check: the modal container exists in the DOM (even if
    // hidden) — confirms the modal plumbing is wired up.
    await expect(page.locator("#mermaid-modal")).toHaveCount(1);
  });

  test("can search via Ctrl+K", async ({ page }) => {
    await page.goto(htmlUrl);

    await page.keyboard.press("Control+k");

    const searchInput = page.locator("#search-input");
    await expect(searchInput).toBeVisible();

    // Search for a common word the DeepWiki index will match in
    // virtually any project (French or English).
    await searchInput.fill("module");
    await expect(page.locator(".search-result").first()).toBeVisible({
      timeout: 5000,
    });
  });
});
